services:
  kafka-1:
    image: confluentinc/cp-kafka:7.6.1 # Specifies the Docker image for the Kafka broker.
    hostname: kafka-1 # Sets the hostname for the container to kafka-1.
    container_name: kafka-1 # Names the container kafka-1 for easy identification.
    ports:
      - "9092:9092" # Maps port 9092 on the host to port 9092 on the container for Kafka traffic.
    environment: # Environment variables for Kafka configuration.
      KAFKA_NODE_ID: 1 # Unique ID for the Kafka broker.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT" # Maps listener names to security protocols.
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092" # Listeners advertised to clients.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3 # Replication factor for the offsets topic.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2 # Minimum in-sync replicas for transaction state log topic.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3 # Replication factor for the transaction state log topic.
      KAFKA_PROCESS_ROLES: "broker,controller" # Roles assigned to the process.
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093" # List of controller quorum voters.
      KAFKA_LISTENERS: "PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://0.0.0.0:9092" # List of listeners with their addresses and ports.
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT" # Listener used for communication between brokers.
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # Listeners used for controller communication.
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs" # Directory for log data.
      KAFKA_METADATA_LOG_DIR: "/tmp/kraft-metadata-logs" # Directory for metadata logs.
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk" # Unique identifier for the Kafka cluster.

  kafka-2:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:29093,PLAINTEXT_HOST://0.0.0.0:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_METADATA_LOG_DIR: "/tmp/kraft-metadata-logs"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  kafka-3:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://localhost:9094"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-3:29092,CONTROLLER://kafka-3:29093,PLAINTEXT_HOST://0.0.0.0:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_METADATA_LOG_DIR: "/tmp/kraft-metadata-logs"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
# services:
#   kafka-1:
#     image: confluentinc/cp-kafka:7.6.1
#     hostname: kafka-1
#     container_name: kafka-1
#     ports:
#       - "9092:9092"
#       - "9101:9101"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_JMX_PORT: 9101
#       KAFKA_JMX_HOSTNAME: localhost
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:29093"
#       KAFKA_LISTENERS: "PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://0.0.0.0:9092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#       # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
#       # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
#       CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
#
# elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
#   container_name: elasticsearch
#   #restart: always
#   healthcheck:
#     start_period: 10s
#     interval: 10s
#     retries: 20
#     test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
#   ports:
#     - 9200:9200
#     - 9300:9300
#   environment:
#     discovery.type: "single-node"
#     ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#     cluster.name: "elasticsearch-cp-demo"
#
# kibana:
#   image: docker.elastic.co/kibana/kibana-oss:7.10.0
#   container_name: kibana
#   restart: always
#   healthcheck:
#     interval: 10s
#     retries: 20
#     test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://kibana:5601/api/status || exit 1
#   depends_on:
#     elasticsearch:
#       condition: service_healthy
#   ports:
#     - 5601:5601
#   environment:
#     NEWSFEED_ENABLED: 'false'
#     TELEMETRY_OPTIN: 'false'
#     TELEMETRY_ENABLED: 'false'
#     SERVER_MAXPAYLOADBYTES: 4194304
#     KIBANA_AUTOCOMPLETETIMEOUT: 3000
#     KIBANA_AUTOCOMPLETETERMINATEAFTER: 2500000
# services:
#   kafka-1:
#     image: apache/kafka:latest
#     hostname: kafka-1
#     container_name: kafka-1
#     ports:
#       - 29092:9092
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
#       KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://localhost:29092
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#
#   kafka-2:
#     image: apache/kafka:latest
#     hostname: kafka-2
#     container_name: kafka-2
#     ports:
#       - 39092:9092
#     environment:
#       KAFKA_NODE_ID: 2
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
#       KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://localhost:39092
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#
#   kafka-3:
#     image: apache/kafka:latest
#     hostname: kafka-3
#     container_name: kafka-3
#     ports:
#       - 49092:9092
#     environment:
#       KAFKA_NODE_ID: 3
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
#       KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092,PLAINTEXT_HOST://localhost:49092
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#
# services:
#   broker:
#     image: apache/kafka:latest
#     hostname: broker
#     container_name: broker
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092"
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
#       KAFKA_LISTENERS: "CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#       KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
#       KAFKA_CREATE_TOPICS: "test"
